/** @type {import('tailwindcss').Config} */
export default {
    content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
    purge: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
    theme: {
        extend: {
            colors: {
                'dark-1': '#024128',
                'dark-2': '#035A37',
                'primary': '#063A45',
                'light-1': '#369A72',
                'light-2': '#68B395',
                'light-3': '#AAD8CD',
                'light-4': '#D4EBE6',
                'light-5': '#E5F3F2',
                'light-6': '#F5F9FA',
                'black': '#1F2120',
                'g-1': '#5F6664',
                'g-2': '#A0A3A2',
                'g-3': '#D1D3D3',
                'g-4': '#E3E5E5',
                'g-5': '#fafbfb',
                'white': '#FFF',
                dialog: {
                    'blue': '#006CE2',
                    'light-blue-1': '#C4DCF5',
                    'light-blue-2': '#E3F0FF',
                    'green': '#1C9D0B',
                    'light-green-1': '#CCF5C9',
                    'light-green-2': '#E7FFE5',
                    'red': '#D91F3C',
                    'light-red-1': '#FAD9DF',
                    'light-red-2': '#FFEDF0',
                    'orange': '#CC7A00',
                    'light-orange-1': '#F5E4CC',
                    'light-orange-2': '#FAF2E6',
                    'purple': '#411884',
                    'light-purple-1': '#E4DAF2',
                    'light-purple-2': '#F4EDFF',
                }
            },
            backgroundColor: {
                'dark-1': '#024128',
                'dark-2': '#035A37',
                'primary': '#063A45',
                'light-1': '#369A72',
                'light-2': '#68B395',
                'light-3': '#AAD8CD',
                'light-4': '#D4EBE6',
                'light-5': '#E5F3F2',
                'light-6': '#F5F9FA',
                'black': '#1F2120',
                'g-1': '#5F6664',
                'g-2': '#A0A3A2',
                'g-3': '#D1D3D3',
                'g-4': '#E3E5E5',
                'g-5': '#fafbfb',
                'white': '#FFF',
                dialog: {
                    'blue': '#006CE2',
                    'light-blue-1': '#C4DCF5',
                    'light-blue-2': '#E3F0FF',
                    'green': '#1C9D0B',
                    'light-green-1': '#CCF5C9',
                    'light-green-2': '#E7FFE5',
                    'red': '#D91F3C',
                    'light-red-1': '#FAD9DF',
                    'light-red-2': '#FFEDF0',
                    'orange': '#CC7A00',
                    'light-orange-1': '#F5E4CC',
                    'light-orange-2': '#FAF2E6',
                    'purple': '#411884',
                    'light-purple-1': '#E4DAF2',
                    'light-purple-2': '#F4EDFF',
                }
            },
            border: {
                'dark-1': '#024128',
                'dark-2': '#035A37',
                'primary': '#063A45',
                'light-1': '#369A72',
                'light-2': '#68B395',
                'light-3': '#AAD8CD',
                'light-4': '#D4EBE6',
                'light-5': '#E5F3F2',
                'light-6': '#F5F9FA',
                'black': '#1F2120',
                'g-1': '#5F6664',
                'g-2': '#A0A3A2',
                'g-3': '#D1D3D3',
                'g-4': '#E3E5E5',
                'g-5': '#fafbfb',
                'white': '#FFF',
                dialog: {
                    'blue': '#006CE2',
                    'light-blue-1': '#C4DCF5',
                    'light-blue-2': '#E3F0FF',
                    'green': '#1C9D0B',
                    'light-green-1': '#CCF5C9',
                    'light-green-2': '#E7FFE5',
                    'red': '#D91F3C',
                    'light-red-1': '#FAD9DF',
                    'light-red-2': '#FFEDF0',
                    'orange': '#CC7A00',
                    'light-orange-1': '#F5E4CC',
                    'light-orange-2': '#FAF2E6',
                    'purple': '#411884',
                    'light-purple-1': '#E4DAF2',
                    'light-purple-2': '#F4EDFF',
                }
            },
            fontFamily: {
                'Almarai': 'Almarai'
            }
        },
    },
    plugins: [],
}

